import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Fragment, useCallback, useRef, useState, useEffect } from "react";

import Button from "@mui/material/Button";
import { Box, fontSize, maxWidth } from "@mui/system";
import { Grid } from "@mui/material";

import Swiper_homePage from "../components/image/home-page/swiper-homePage";

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swiper_homePage />
    </main>
  );
};

export default Home;

export function getStaticProps() {
  // when one of the page is loaded, the props returned from getServerSide/StaticProps
  // of the current page will be automatically passed to the _app.js and merged to
  // the "pageProps". So we can tell the "navigation" inside the "Layout" that
  // which page we are currently in, then change the navigation bar accordingly

  return { props: { page: "home" } };
}
