import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "@mui/material/Button";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home Page</h1>
        <Image
          src="https://testing-images-on-s3.s3.us-east-2.amazonaws.com/images/cat-mask.jpg"
          alt="aws"
          // unoptimized={true}
          width={300}
          height={300}
        />
      </main>
      <Button variant="outlined" color="secondary">
        Primary
      </Button>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export function getStaticProps() {
  // when one of the page is loaded, the props returned from getServerSide/StaticProps
  // of the current page will be automatically passed to the _app.js and merged to
  // the "pageProps". So we can tell the "navigation" inside the "Layout" that
  // which page we are currently in, then change the navigation bar accordingly

  return { props: { page: "home" } };
}
